services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: dernpa
      POSTGRES_PASSWORD: dernpa
      POSTGRES_DB: dernpa
    ports:
      - "5433:5432"
    volumes:
      - dernpa_pg:/var/lib/postgresql/data

volumes:
  dernpa_pg:
